drone:  
  model_name: "hummingbird"
  randomization:
    eval:
      mass_scale: [0.8, 1.2]        # mass ±20%
      inertia_scale: [0.8, 1.2]     # inertia ±20%
      t2w_scale: [0.9, 1.1]         # thrust coefficient ±10%
      f2m_scale: [0.9, 1.1]         # moment coefficient ±10%

sensor:
  lidar_range: 4.
  lidar_vfov: [-10, 20.] # degree
  lidar_vbeams: 4 # number of vertical beams
  lidar_hres: 10. # degree
  